version: '2'
services:
  node-container:
    image: vposvistelik/node:6.7-dev
    volumes:
      - ./../:/app
      - ./node-container-files/npm-bin-exec.sh:/usr/bin/npm-bin-exec:ro
    environment:
      LOCAL_USER_ID: 1000
